export const CHANGE_JOB_TITLE = "CHANGE_JOB_TITLE";
export const CHANGE_LOCATION = "CHANGE_LOCATION";
export const CHANGE_DESCRIPTION = "CHANGE_DESCRIPTION";
export const CHANGE_JOB_TYPE = "CHANGE_JOB_TYPE";